WebApplication1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Filter;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AboutController : Controller
    {
        private DbModel db = new DbModel();

        [AddLayoutBreadcrumb("controller")]
        [AddLayoutSidebar("controller")]
        [AddLayoutMenu]
        public ActionResult Index()
        {
            string controllerName = RouteData.Values["controller"].ToString();
            var HtmlContent = db.Directory.FirstOrDefault(x => x.Value == controllerName).WebContentTable.FirstOrDefault();
            return View(HtmlContent);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切換導覽" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("首頁", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("關於", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_LayoutFire.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>國際縱火調查人員協會臺灣分會-@ViewBag.Title</title>
    @Styles.Render("~/Content/FireCss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="body-inner">

        <!-- Header start -->
        <header id="header" class="header-solid">
            <div class="container">
                <div class="row">
                    <div class="logo col-md-6 col-sm-7 col-xs-12 ">
                        <a href="/">
                            <img src="/images/logo.png" alt="國際縱火調查人員協會臺灣分會" title="國際縱火調查人員協會臺灣分會">
                        </a>
                    </div><!-- logo end -->

                    <div class="col-md-6 col-sm-5 col-xs-12 header-right">

                        <ul class="top-info">
                            <li>
                                <div class="info-box">
                                    <a href="https://www.facebook.com/groups/386043368203748/" title="粉絲專頁" target="_blank">
                                        <i class="fa fa-facebook">&nbsp;</i>
                                        <div class="info-box-content">
                                            <p class="info-box-title">粉絲專頁</p>
                                        </div>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="info-box">
                                    <a rel="alternate" hreflang="en" href="/en/home" title="English">
                                        <i class="fa fa-globe">&nbsp;</i>
                                        <div class="info-box-content">
                                            <p class="info-box-title">English</p>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div><!-- header right end -->
                </div><!-- Row end -->
            </div><!-- Container end -->
        </header><!--/ Header end -->

        <nav class="site-navigation navigation">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="site-nav-inner">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <div class="collapse navbar-collapse navbar-responsive-collapse">

                                <ul class="nav navbar-nav">
                                    <li class="dropdown active">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="關於我們">關於我們 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Article/About">關於我們</a></li>
                                            <li><a href="/Article/Organization">組織架構</a></li>
                                            <li><a href="/Article/history">沿革</a></li>
                                            <li><a href="/Article/Member">配證會員</a></li>
                                            <li><a href="/Expert">專家介紹</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="訊息發佈">訊息發佈 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/news">最新消息</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="會員專區">會員專區 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Download">討論區</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="協會業務">協會業務 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Article/Job">協會業務</a></li>
                                            <li><a href="/Article/Licenses">訓練、認證、發照</a></li>
                                            <li><a href="/Article/Refer">諮詢、顧問</a></li>
                                            <li><a href="/Article/Survey">縱火調查</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="知識庫">知識庫 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Knowledge">知識庫下載</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="行事曆">行事曆 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Article/Calendar">協會行事曆</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="聯絡我們">聯絡我們 <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Contact">聯絡我們</a></li>
                                        </ul>
                                    </li>
                                </ul><!--/ Nav ul end -->

                            </div><!--/ Collapse end -->

                        </div><!-- Site Navbar inner end -->


                    </div><!--/ Col end -->
                </div><!--/ Row end -->
            </div><!--/ Container end -->
        </nav><!--/ Navigation end -->

        <div id="banner-area" class="banner-area" style="background-image:url(/images/banner-bg.jpg)">
            <!-- Subpage title start -->
            <div class="banner-text text-right">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">

                            <ul class="breadcrumb">
                                <li>首頁</li>
                                <li>關於我們</li>
                                <li><a href="#">關於我們</a></li>
                            </ul>


                        </div>
                    </div>
                </div>
            </div><!-- Subpage title end -->
        </div><!-- Banner area end -->

        <section id="main-container" class="main-container">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">

                        <div class="sidebar sidebar-right">

                            <div class="widget">
                                <h2 class="widget-title"><i class="fa fa-folder-open-o">&nbsp;</i>關於我們</h2>
                                <ul class="arrow nav nav-tabs nav-stacked">
                                    <li class="active"><a href="/Article/About">關於我們</a></li>
                                    <li><a href="/Article/Organization">組織架構</a></li>
                                    <li><a href="/Article/history">沿革</a></li>
                                    <li><a href="/Article/Member">配證會員</a></li>
                                    <li><a href="/Expert">專家介紹</a></li>
                                </ul>
                            </div>

                            <!-- Categories end -->

                        </div><!-- Sidebar end -->
                    </div><!-- Sidebar Col end -->

                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">


                        @RenderBody()





                        <!-- Content row 1 end -->
                        <!-- 內容結束 -->

                        <div class="tags-area clearfix">

                            <div class="share-items pull-right" style="display: none">
                                <ul class="post-social-icons unstyled">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>

                    </div><!-- Content Col end -->


                </div><!-- Main row end -->

            </div><!-- Conatiner end -->
        </section><!-- Main container end -->
        <!-- Footer start -->
        <footer id="footer" class="footer">
            <div class="container">

                <div class="row copyright">
                    <div class="col-xs-12 col-sm-7">
                        <div class="copyright-info">
                            <span>
                                國際縱火調查人員協會臺灣分會版權所有<br>
                                Copyright © 2016 International Association of Arson Investigators Taiwan Chapter. All Rights Reserved.
                            </span>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-push-1">

                        <div class="footer-menu">
                            <a class="btn btn-dark" href="/Article/Declare" title="財產權宣告">財產權宣告</a>
                        </div>
                    </div>
                </div><!-- Copyright end -->

                <div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top affix">
                    <button class="btn btn-primary" title="Back to Top">
                        <i class="fa fa-angle-double-up"></i>
                    </button>
                </div>

            </div><!--/ Container end -->
        </footer><!-- Footer end -->
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>



<!--RenderBody內容
<h2 class="page-title">關於我們</h2>
<hr class="botmargin-min">-->
<!-- 內容開始 -->
<!--<div class="clearfix _2pi4">
</div>-->

WebApplication1/Views/Shared/_LayoutHomePage.cshtml
@*@model WebApplication1.Models.ViewModels.DirectoryFrontViewModel*@

<!DOCTYPE html>
<html>
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">


    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />

    <title>國際縱火調查人員協會臺灣分會-@ViewBag.Title</title>
    @Styles.Render("~/Content/SampleCSSFolder")


</head>

<body>

    <div class="body-inner">
        <!-- Header start -->
        <header id="header" class="header-solid">
            <div class="container">
                <div class="row">
                    <div class="logo col-md-6 col-sm-7 col-xs-12 ">
                        <a href="/Home/Index">
                            <img src="/images/logo.png" alt="國際縱火調查人員協會臺灣分會" title="國際縱火調查人員協會臺灣分會">
                        </a>
                    </div><!-- logo end -->

                    <div class="col-md-6 col-sm-5 col-xs-12 header-right">

                        <ul class="top-info">
                            <li>
                                <div class="info-box">
                                    <a href="#top" title="粉絲專頁">
                                        <i class="fa fa-facebook">&nbsp;</i>
                                        <div class="info-box-content">
                                            <p class="info-box-title">粉絲專頁</p>
                                        </div>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="info-box">
                                    <a href="#top" title="English">
                                        <i class="fa fa-globe">&nbsp;</i>
                                        <div class="info-box-content">
                                            <p class="info-box-title">English</p>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div><!-- header right end -->
                </div><!-- Row end -->
            </div><!-- Container end -->
        </header>
        <!--/ Header end -->
        <!--Navigation start -->
        <nav class="site-navigation navigation">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="site-nav-inner">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <div class="collapse navbar-collapse navbar-responsive-collapse">

                              @Html.Raw(@ViewBag.MenuResult)
                                <!--<ul class="nav navbar-nav">
                                <li class="dropdown active">
                                    <a href="about.html" class="dropdown-toggle" data-toggle="dropdown" title="關於我們">關於我們 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li class="active"><a href="about.html">協會介紹</a></li>
                                        <li><a href="master.html">專家介紹</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="news.html" class="dropdown-toggle" data-toggle="dropdown" title="訊息發佈">訊息發佈 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="news.html">最新消息</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="member.html" class="dropdown-toggle" data-toggle="dropdown" title="會員專區">會員專區 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="member_login.html">會員登入</a></li>
                                        <li><a href="member_dl.html">檔案下載</a></li>
                                        <li><a href="member_reg.html">會員註冊</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="business.html" class="dropdown-toggle" data-toggle="dropdown" title="協會業務">協會業務 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="business.html">協會業務</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="knowledge.html" class="dropdown-toggle" data-toggle="dropdown" title="知識庫">知識庫 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="knowledge.html">知識庫下載</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="calendar.html" class="dropdown-toggle" data-toggle="dropdown" title="行事曆">行事曆 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="calendar.html">協會行事曆</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="contact.html" class="dropdown-toggle" data-toggle="dropdown" title="聯絡我們">聯絡我們 <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="contact.html">聯絡我們</a></li>
                                    </ul>
                                </li>
                            </ul>-->
                                <!--/ Nav ul end -->

                            </div><!--/ Collapse end -->
                        </div><!-- Site Navbar inner end -->
                    </div><!--/ Col end -->
                </div><!--/ Row end -->
            </div><!--/ Container end -->
        </nav><!--/ Navigation end -->


        @RenderBody()


        <!-- Footer start -->
        <footer id="footer" class="footer">
            <div class="container">

                <div class="row copyright">
                    <div class="col-xs-12 col-sm-7">
                        <div class="copyright-info">
                            <span>
                                火箭隊後端專題實作<br>
                                Copyright © 2024 Rocket Team Backend Project. All Rights Reserved.
                            </span>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-push-1">

                        <div class="footer-menu">
                            <a class="btn btn-dark" href="#" title="財產權宣告">財產權宣告</a>
                        </div>
                    </div>
                </div><!-- Copyright end -->

                <div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top affix">
                    <a class="btn btn-primary" title="Back to Top" href="#top">
                        <i class="fa fa-angle-double-up"></i>
                    </a>
                </div>

            </div><!--/ Container end -->
        </footer><!-- Footer end -->
        <!-- Javascript Files
    ================================================== -->
        @Scripts.Render("~/bundles/SampeJSFolder")
        @RenderSection("scripts", required: false)
    </div><!-- Body inner end -->
</body>
</html>

WebApplication1/Views/Shared/_PartialBanner.cshtml
@model  IEnumerable<WebApplication1.Models.Directory>


@foreach (var item in Model)
{
    if (item.RecursiveId == null)
    {
        <li>@item.Title</li>
    }
    else
    {
        <li><a href="/Home/@item.Value">@item.Title</a></li>
    }
}

WebApplication1/Views/Shared/_PartialSideBar.cshtml
@model  IEnumerable<WebApplication1.Models.Directory>


@foreach (var item in Model)
{
    if (item.RecursiveId == null)
    {
        <h2 class="widget-title"><i class="fa fa-folder-open-o">&nbsp;</i>@item.Title</h2>
    }
}
<ul class="arrow nav nav-tabs nav-stacked">
    @foreach (var item in Model)
    {
        if (item.RecursiveId != null)
        {
            <li><a href="/Home/@item.Value">@item.Title</a></li>
        }
    }
</ul>